modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="loyalhoemod"
version="1.16.3-0.1"
displayName="Loyal Hoe Mod"
authors="Raymonzut"
description='''
Adds more meaning to the hoe
'''

[[dependencies.loyalhoemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.loyalhoemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
